name: my_store_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.4
  cloudinary_public: ^0.23.1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.5
  rive: ^0.13.20
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0 # Already up to date
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true # Ensure this is directly under 'flutter:' and not duplicated.

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/RiveAssets/
    - assets/Backgrounds/
    - assets/icons/
    - assets/avaters/
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
# For Flutter's localization generation (MUST BE AT TOP LEVEL, NOT UNDER 'flutter:')
flutter_gen_l10n:
  enabled: true
  arb-dir: lib/l10n # Path to your .arb files
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
