// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7V3JBlRdPKwfkZ7cesNDDX9usLyS5Mg',
    appId: '1:491773887662:web:ff4fc49cbfab5c486f593f',
    messagingSenderId: '491773887662',
    projectId: 'storeapp-975b9',
    authDomain: 'storeapp-975b9.firebaseapp.com',
    storageBucket: 'storeapp-975b9.firebasestorage.app',
    measurementId: 'G-33BEL85WGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1ru4ooYJ4GnOrJw6f_jBZRXm1KAY2WI',
    appId: '1:491773887662:android:e83d99834bf25a9c6f593f',
    messagingSenderId: '491773887662',
    projectId: 'storeapp-975b9',
    storageBucket: 'storeapp-975b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOTpjP0Sek222UMr1Mpon1_jkSi-X4zQA',
    appId: '1:491773887662:ios:9b09d3be155dd1bd6f593f',
    messagingSenderId: '491773887662',
    projectId: 'storeapp-975b9',
    storageBucket: 'storeapp-975b9.firebasestorage.app',
    iosBundleId: 'com.example.myStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm7V3JBlRdPKwfkZ7cesNDDX9usLyS5Mg',
    appId: '1:491773887662:web:abdabc86ee2f2efb6f593f',
    messagingSenderId: '491773887662',
    projectId: 'storeapp-975b9',
    authDomain: 'storeapp-975b9.firebaseapp.com',
    storageBucket: 'storeapp-975b9.firebasestorage.app',
    measurementId: 'G-RWNMV6ZMGV',
  );
}
